# ADSP 31014 — Statistical Models for Data Science
## Homework 1

**Name:** Obaro Erigha    
**Term:** Autumn 2026    

**External Sources:** Claude for Q13 as requested

---

 Let’s consider two discrete random variables 𝑋 and 𝑌 with the following (joint) probability mass function.

In [47]:
import pandas as pd
import numpy as np


data = [
    # x, y, p_x,y(x,y) = P(X=x, Y=y)
    (-1, 1, 0.06),
    (-1, 2, 0.10),
    (-1, 4, 0.04),
    ( 0, 1, 0.21),
    ( 0, 2, 0.35),
    ( 0, 4, 0.14),
    ( 2, 1, 0.03),
    ( 2, 2, 0.05),
    ( 2, 4, 0.02) 
]

df = pd.DataFrame(data, columns=['x', 'y', 'p_x_y'])
df

   x  y  p_x_y
0 -1  1   0.06
1 -1  2   0.10
2 -1  4   0.04
3  0  1   0.21
4  0  2   0.35
5  0  4   0.14
6  2  1   0.03
7  2  2   0.05
8  2  4   0.02

#### Question 1
 Compute the (marginal) probability mass function of 𝑋 by “summing over the probabilities of 𝑌”.

In [48]:
p_X = df.groupby("x")["p_x_y"].sum()

print(p_X)

x
-1    0.2
 0    0.7
 2    0.1
Name: p_x_y, dtype: float64

#### Question 2
Compute the expectation 𝔼(𝑋) of 𝑋.

In [49]:
# print(p_X.index)
# print(p_X.index * p_X)

E_X = (p_X.index * p_X).sum()

print(E_X)

0.0

#### Question 3
Compute the Variance Var(𝑋) of 𝑋.

In [50]:

# print((p_X.index**2 * p_X).sum())

E_X2 = (p_X.index**2 * p_X).sum() # E(X^2)

Var_X = E_X2 - E_X**2

print(round(Var_X, 4))

0.6

#### Question 4
Compute the standard deviation SD(𝑋) = sqrt(Var(𝑋)) of 𝑋

In [51]:
SD_X = Var_X**0.5

print(SD_X)

0.7745966692414834

#### Question 5
Similarly, compute the (marginal) probability mass function 𝑝𝑌(𝑦), expectation 𝔼(𝑌), variance Var(𝑌), and standard deviation SD(𝑌) of 𝑌.

In [52]:
p_Y = df.groupby('y')["p_x_y"].sum()

print(p_Y) # marginal probability mass function 𝑝𝑌(𝑦)

E_Y = (p_Y.index * p_Y).sum()

print(round(E_Y, 4)) # expectation 𝔼(𝑌)

E_Y2 = (p_Y.index**2 * p_Y).sum() # E(Y^2)

Var_Y = E_Y2 - E_Y**2

print(round(Var_Y, 4)) # variance Var(𝑌)

SD_Y = Var_Y**0.5 

print(round(SD_Y, 4)) # standard deviation SD(𝑌)

y
1    0.3
2    0.5
4    0.2
Name: p_x_y, dtype: float64
2.1
1.09
1.044

#### Question 6
Compute the covariance Cov(𝑋, 𝑌) of 𝑋 and 𝑌.

In [53]:
E_XY = (df["x"] * df["y"] * df["p_x_y"]).sum()

print(round(E_XY,4)) # expectation of the product 𝔼(𝑋𝑌)

Cov_XY = E_XY - E_X * E_Y

print(round(Cov_XY,4)) # covariance Cov(𝑋,𝑌)

-0.0
-0.0

#### Question 7
Compute the correlation Corr(𝑋, 𝑌) of 𝑋 and 𝑌.

In [56]:
SD_X = Var_X ** 0.5
SD_Y = Var_Y ** 0.5

Corr_XY = Cov_XY / (SD_X * SD_Y)

print(round(Corr_XY, 4)) # correlation Corr(𝑋,𝑌)

-0.0

#### Question 8
Based on Question 7, are random variables 𝑋 and 𝑌 correlated or uncorrelated?

Corr_XY = 0, Therefore 𝑋 and 𝑌 are uncorrelated.

#### Question 9
Based on Question 1 and 5, if we write the values of the marginal probability mass functions of 𝑋 and 𝑌 as column and row vectors respectively;


Perform matrix multiplication to obtain a 3 × 3 matrix

In [55]:
p_X_vec = p_X.values.reshape(-1, 1)   # column vector (3×1)
p_Y_vec = p_Y.values.reshape(1, -1)   # row vector   (1×3)

outer_product = p_X_vec @ p_Y_vec     # (3×1) @ (1×3) = 3×3
outer_df = pd.DataFrame(outer_product, index=p_X.index, columns=p_Y.index)
outer_df

y      1     2     4
x
-1  0.06  0.10  0.04
 0  0.21  0.35  0.14
 2  0.03  0.05  0.02

#### Question 10
If we write the values of the joint probability mass function of (𝑋, 𝑌) as a 3 × 3 matrix. 

What is the relationship between this matrix and the one in Question 9? (Hint: The answer should be simple and obvious.)

They are the same.

#### Question 11
Based on Question 10, are random variables 𝑋 and 𝑌 independent or not? 

The random variables 𝑋 and 𝑌 are independent as the joint probability matrix is the same as the px * py 3x3 matrix.

eg.
P(X=x,Y=y)=P(X=x)⋅P(Y=y)

#### Question 12
To model the relationship of positive quantities (e.g. 𝑥𝑥 = “infection rate of an apocalyptic virus” and 𝑦𝑦= 
“number of zombies”), we sometimes consider an exponential growth model form 
 
𝑦= 𝛽0(𝑥^𝛽1)𝜖  with parameters 𝛽0 > 0 and 𝛽1 ∈ℝ, and a multiplicative positive noise term 𝜖 > 0.  Can this model be viewed as a linear model?                    Explain.  (Hint: Take logarithm.) 

Yes.

You can rewrite this by taking the logarithm of both sides of the formula as follows:

1. log(𝑦) = log(𝛽0(𝑥^𝛽1)𝜖)
2. log(𝑦) = log(𝛽0) + 𝛽1*log(𝑥) + log(𝜖)

𝑦' = log(𝑦)
𝑥' = log(𝑥)
𝛽0' = log(𝛽0)
𝜖' = log(𝜖)

𝑦' = 𝛽0' + 𝛽1*𝑥' + 𝜖'

#### Question 13
Write a GenAI prompt to describe our Chicago taxi trip data set and its nature (e.g. column names) and ask some GenAI tool (e.g. ChatGPT, Gemini, Claude) for potential data issues to be aware of when performing data cleaning and exploratory data analysis on this data set.  What does GenAI say? How good are the suggestions?  Is there any suggestion that we have not thought of?

#### Prompt:
I'm a data analyst about to clean and explore a public dataset: Chicago taxi
trips for calendar year 2022, from the City of Chicago Data Portal ("Taxi
Trips"). It has ~6.4 million rows (one row per trip) and 23 columns. I plan on using Python to perform the cleaning. 

The columns are:
- Trip ID, Taxi ID: hashed strings (Trip ID is unique)
- Trip Start Timestamp, Trip End Timestamp: strings like "01/01/2022 12:00:00 AM"
- Trip Seconds, Trip Miles: floats
- Pickup/Dropoff Census Tract: 11-digit codes, loaded as float
- Pickup/Dropoff Community Area: integer codes 1-77, loaded as float
- Fare, Tips, Tolls, Extras, Trip Total: USD floats
- Payment Type, Company: categorical strings
- Pickup/Dropoff Centroid Latitude, Longitude: floats
- Pickup/Dropoff Centroid Location: WKT strings, e.g. "POINT (-87.63 41.89)"

Please look out for potential data issues I should be aware of when cleaning
and doing exploratory data analysis on this dataset.

#### Response & Suggestions:
Potential data issues: Chicago Taxi Trips 2022
A. Cross-cutting issues (highest importance)

1. Missingness is structural, not random

Why: The city masks locations for privacy (low-volume tracts, trips outside Chicago). Some companies or payment types may not report fare fields at all.
Detect: df.isna().groupby(df['Company']).mean(), and the same by Payment Type, month and area.
Handle: Treat missingness as information. Report which groups it hits before dropping or imputing.
Risk: Silent bias toward certain companies, payment types or neighborhoods.

2. Bias introduced by the cleaning itself

Why: Dropping rows with missing fares or locations removes disproportionate shares of certain groups (for example, cash trips or low-density areas).
Detect: Compare payment mix, hour-of-day, company share and area distribution before and after cleaning.
Handle: Document what was removed and why. Test whether conclusions change under looser or stricter thresholds.
Risk: Conclusions that apply only to the surviving subset.

3. Arbitrary outlier thresholds

Why: Cutoffs such as "under 2 hours" or "under 100 miles" are judgment calls.
Handle: Run a sensitivity check at several thresholds, and keep a log of rows removed per rule.
B. Timestamps

4. Parsing and rounding

Strings need pd.to_datetime(..., format='%m/%d/%Y %I:%M:%S %p'). Timestamps are very likely rounded to 15-minute intervals for privacy, so derived durations are only approximate.

5. Daylight saving time

Times are local and timezone-naive. The spring-forward date has a missing hour that can make derived durations wrong by an hour. The fall-back date has a repeated hour that creates ambiguity and apparent negative durations.
Detect: Compare Trip Seconds against End − Start and look at where the disagreements cluster by date.

6. Logical and range errors

End before start, years outside 2022 (end dates can legitimately spill into Jan 2023), and zero-length trips.
Detect: df[df.start > df.end], df.end.dt.year.value_counts().
C. Trip Seconds and Trip Miles

7. Zeros and extremes

Expect many zeros (cancelled trips, meter glitches), 24-hour trips, and distances in the thousands of miles. Zero miles with nonzero time, and zero time with nonzero miles, are both common.
Handle: Define a plausible range (for example 1 s to a few hours, 0.01 to ~100 miles) and justify it.

8. Implied speed (often overlooked)

Range filters on each column separately miss combinations such as 50 miles in 3 minutes.
Detect: speed = miles / (seconds / 3600), then inspect the upper tail and drop physically impossible speeds (for example above ~80 mph).

9. Duration consistency

Trip Seconds and timestamp difference should agree within the 15-minute rounding tolerance. Large gaps indicate a bad record.
D. Money columns

10. Zero, tiny and absurd values

Zero or one-cent fares, fares in the thousands, and trips where tolls or extras are in the thousands. Taxi fares have a base amount, so anything below it is suspect.
Detect: df['Fare'].value_counts().sort_index().head(20) and .nlargest(20).

11. Cash tips are not recorded

Tips are typically captured only for card or mobile payments. For cash, Tips = 0 means "unknown", not "no tip".
Handle: Analyze tipping only on non-cash payments.
Risk: Badly understated tip rates, and a spike at zero in any tip histogram.

12. Components may not sum to Trip Total

Taxes, surcharges or other fees may not appear in any column.
Detect: Use np.isclose(...) or round to cents. Comparing floats with == produces false mismatches from rounding error.

13. Spikes at fixed amounts

Base fare, flat airport rates and standard surcharges create peaks at specific values. These are real, not errors. Don't "fix" them.
E. Location columns

14. Centroids, not true positions

Pickup and dropoff coordinates are centroids of tracts or community areas, so many trips share identical points and the number of unique coordinates is small.
Risk: Distance computed from coordinates is crude, and maps look gridded. Don't treat them as GPS data.

15. Redundant and inconsistent columns

Lat, lon and the WKT string carry the same information. Parse the WKT and confirm it matches. Keep one representation.

16. Codes stored as floats

Census tracts are 11-digit identifiers and community areas are integers 1–77. NaNs force them to float. Convert to string or nullable Int64.

17. Tract vs community area availability

Often only one of the two is present. Decide which is your location key.
F. Categorical columns

18. Company names

Spelling and case variants, trailing "Inc." or ", LLC", truncated names, and owner-operator entries labeled with ID numbers.
Detect: df['Company'].value_counts().sort_index() and merge near-duplicates.

19. Payment type

Categories such as Unknown, Dispute, No Charge and Prcard. "Unknown" may reflect one company's reporting practice, not a real payment method. Check the company × payment type table before merging categories.
Dispute and No Charge rows usually have unreliable fares.
G. IDs and duplicates

20. Taxi ID is a vehicle, not a driver

Counts per taxi are heavily skewed, and busy taxis are likely shared across drivers and shifts.
Detect: Sort by Taxi ID and start time, and flag overlapping trips. A single taxi cannot be on two trips at once.

21. Hidden duplicates

Trip ID may be unique while the underlying trip is duplicated. Check duplicates on all other columns.
H. Context and technical

22. 2022 context

It was a post-COVID recovery year. Low January volume, seasonality, weather and holidays are real patterns, not data errors. Weekday and hour effects are strong.

23. Memory and dtypes

At ~6.4M rows × 23 columns, the data is about 3 GB in pandas. Use category for company and payment type, downcast numerics, and drop redundant columns early. Consider parquet over CSV.
Suggested order of work
Parse types and check missingness structure.
Fix logical errors (timestamps, DST, ranges).
Check cross-field consistency (speed, duration, money).
Standardize categories.
Apply filters, logging the rows removed per rule.
Compare before and after distributions to check for bias.

I only have the schema, not the values. The detection steps above should confirm which of these issues actually appear in your data.

#### Quality of Suggestions
Gave a good checlist of suggestions, but a bit generic as it only had descriptions of the dataset. The notebook addresses most of the standard issues but there were a few interesting suggestions that were missed.
1. Implied speed check to Compute miles per hour and drop physically impossible speeds.
2. Cash tips are not recorded. Tips = 0 for cash likely means "unknown", not "no tip", which distorts the tip analysis. Analyze tipping only for card and mobile payments.
3. Float equality bug. Comparing Fare + Tips + Tolls + Extras == Trip Total with == overstates the 27% mismatch because of rounding.
4. Bias from our own cleaning. We dropped 25% of rows, and the dropped rows are skewed toward cash payments and privacy-masked locations. Compare distributions before and after cleaning and state the limitation.
5. Overlapping trips per taxi. A single taxi cannot be on two trips at once, so overlaps reveal duplicate or bad records that row-by-row checks miss.
6. Payment type merging. Collapsing Mobile, Prcard and Unknown into "Other" loses information. "Unknown" is largely one company's reporting artifact.
7. Fall-back daylight saving (November). We caught the March spring-forward problem but not the repeated hour in November.
8. Centroid limits and threshold sensitivity. Coordinates are area centroids, so distances from them are crude, and cutoffs like 2 hours, 100 miles and $200 should be tested for sensitivity.